name: Swift CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  exec-ci:
    runs-on: macos-11

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Reconfigure Private Repo URLs
        run: git config --global --add url."ssh://${{ secrets.ACCESS_TOKEN }}@github.com/Morgan2010".insteadOf "ssh://git@github.com/Morgan2010"

      - name: Run tests
        run: swift test --enable-code-coverage

      - name: Coverage report
        uses: maxep/spm-lcov-action@0.3.1
        with:
          output-file: ./coverage/lcov.info
